function plotBlockScalp(data, chanlocs, varargin)
parser = inputParser();
parser.addRequired('Data', ...
    @(x) validateattributes(x, {'numeric'}, ...
    {'vector', 'nonempty'}));
parser.addRequired('Chanlocs', ...
    @(x) validateattributes(x, {'struct'}, ...
    {'nonempty', 'numel', numel(data)}));
parser.addParamValue('InterpolationMethod', 'v4', ...
    @(x) any(strcmpi(x, {'v4', 'linear', 'cubic', 'nearest'})))
parser.addParamValue('ShowColorbar', true, ...
    @(x) validateattributes(x, {'logical'}, ...
    {'nonempty'}));
parser.addParamValue('HeadColor', [0.75, 0.75, 0.75], ...
    @(x) validateattributes(x, {'numeric'}, ...
    {'vector', 'nonempty', 'numel', 3}));
parser.addParamValue('ElementColor', [0, 0, 0], ...
    @(x) validateattributes(x, {'numeric'}, ...
    {'vector', 'nonempty', 'numel', 3}));
parser.parse(data, chanlocs, varargin{:});
pdata = parser.Results;
fig1 = figure('Name', 'Block Scalp Plot');
sm1 = visviews.blockScalpPlot(fig1, [], []);
sm1.plot(pdata.Data, pdata.Chanlocs, pdata.InterpolationMethod, ...
    pdata.ShowColorbar, pdata.HeadColor, pdata.ElementColor);
gaps = sm1.getGaps();
sm1.reposition(gaps);
end

