classdef baseTestClass < hgsetget
    % Settings test class
    properties
        Background;
        BlockName;
        BlockSize;
        BoxColors;
        BoxLimits;
        Counter;
        SimpleInteger;
        WindowType;   
    end % properties
    
  
    methods
        function obj = baseTestClass()  
            
        end % TestClass constructor   
    end % methods
    
    methods (Static = true)
        function settings = getDefaults()
            % Field name, class name, class modifier, display name, type, default, options,
            % descriptions
            cName = 'baseTestClass';
            settings = struct( ...
                 'Enabled',      {true,         true,           true,                true,                     true,                 true,                true,               true}, ...                                       
                 'ID',           {'BlockName', 'BlockSize'     'WindowType',        'BoxColors',               'BoxLimits',         'Background',        'Counter',           'SimpleInteger'}, ...
                 'Category',      {cName,        cName,         cName,               cName,                     cName,               cName,                cName,              cName}, ...
                 'DisplayName',   {'Block name', 'Block size',  'Window type',       'Box plot colors',         'Box plot limits',   'Background color',   'Count',            'Range integer'}, ...
                 'Type',          {'string',     'double',      'enumerated',        'colorList',               'interval',           'color',             'unsignedInteger',  'integer'}, ...
                 'Value',         {'Window',     1000,          'Blocked',            [0.7, 0.7, 0.7; 1, 0, 1],  [-inf, inf],         [0.7, 0.7, 0.7],     0,                  1}, ...
                 'Editable',      {true,         true,          true,                 true,                     true,                 true,                 true,              true}, ...
                 'Options',       {'',           [0, inf],      {'Blocked', 'Epoched'},  '',                        '',               '',                   '',                ''}, ...
                 'Definition',          {'string',     'double',      'enumerated',        'colorList',               'interval',           'color',             'unsignedInteger',  'integer'}, ...
                 'Description',   {'Block name or label (e.g. ''Window'')', ...
                                   'Block size for computation (must be positive)', ...
                                   'Window type must be either ''Window'' or ''Epoch''', ...
                                   'BlockBoxPlot alternating box colors (cannot be empty)', ...
                                   'BlockBoxPlot limits', ...
                                   'Background color designating no activity', ...
                                   'Counter of objects', ...
                                   'Integer example'} ...
                                   );
        end

    end % static methods
    
end % ModelSettingsTestClass
