%% Publish the documentation in this directory
%


%% Set up for the scripts:
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
scriptNames = {'eegvis_features', ...
               'eegvis_functions_by_cat', ...
               'eegvis_product_page', ...
               'eegvis_getting_started', ...
               'eegvis_release_notes', ...
               'eegvis_system_requirements', ...
               'eegvis_user_guide'};

for k = 1:length(scriptNames)
   publish([scriptNames{k} '.m'], publish_options);
end

%% Publish the function scripts
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
topLevelScripts = { ...
              'eegbrowse_help', ...
              'eegplugin_eegvis_help', ...
              'eegvis_help', ...
              'pop_eegbrowse_help', ...
              'pop_eegvis_help' ...
              };
          
for k = 1:length(topLevelScripts)
   publish([topLevelScripts{k} '.m'], publish_options);
end

%% Publish the function scripts
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
coreScripts = { ...
              'blockedData_help', ...
              'counter_help', ...
              'dataConfig_help', ...
              'dataManager_help', ...
              'dataSelector_help', ...
              'dataSlice_help', ...
              'managedObj_help', ...
              'tableConfig_help', ...
              'tablePanel_help' ...
              };
          
for k = 1:length(coreScripts)
   publish([coreScripts{k} '.m'], publish_options);
end


%% Publish the function scripts
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
funcScripts = { ...
              'functionConfig_help', ...
              'functionObj_help' ...
              };
          
for k = 1:length(funcScripts)
   publish([funcScripts{k} '.m'], publish_options);
end

%% Publish the property scripts
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
propertyScripts = { ...
              'colorListProperty_help', ...
              'colorProperty_help', ...
              'configurable_help', ...
              'configurableObj_help', ...
              'doubleProperty_help', ...
              'enumeratedProperty_help', ...
              'integerProperty_help', ...
              'intervalProperty_help', ...
              'logicalProperty_help' ...
              'property_help', ...
              'propertyConfig_help', ...
              'stringListProperty_help', ...
              'stringProperty_help', ...
              'unsignedIntegerProperty_help', ...
              'vectorProperty_help', ...
              'javaclass_help' ...              
              };
          
for k = 1:length(propertyScripts)
   publish([propertyScripts{k} '.m'], publish_options);
end


%% Publish the visualization scripts
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
viewScripts = { ...
              'axesPanel_help', ...
              'blockBoxPlot_help', ...
              'blockHistogramPlot_help', ...
              'blockImagePlot_help', ...
              'blockScalpPlot_help', ...
              'clickable_help', ...
              'cursorExplorable_help', ...
              'cursorExplorer_help', ...
              'dualView_help', ...
              'elementBoxPlot_help' ...
              'horizontalPanel_help', ...
              'plotConfig_help', ...
              'plotObj_help', ...
              'resizable_help', ...
              'signalHistogramPlot_help', ...
              'signalShadowPlot_help', ...
              'signalStackedPlot_help' ...      
              'tabPanel_help', ...
              'verticalPanel_help' ...
              };
          
for k = 1:length(viewScripts)
   publish([viewScripts{k} '.m'], publish_options);
end

